'use client';
import {useEffect,useState} from 'react';
import {createClient} from '@supabase/supabase-js';
import MobileNavigation from '../components/MobileNavigation';
import FinanceModule from '../components/FinanceModule';
import StudyModule from '../components/StudyModule';
import {planDay} from '../lib/planner.mjs';
import {fieldLimits,prepareRow} from '../lib/forms.mjs';
const tables=['profiles','routine_settings','work_shifts','daily_plans','activities','weekly_goals','uber_sessions','study_sessions'];
const labels={gym:'Academia',study:'Estudos',english:'Inglês',uber:'Uber',work:'Trabalho',commute:'Deslocamento',leisure:'Descanso'};
const modes={auto:'Automático',home:'Casa',uber_return:'Uber de retorno',uber_focused:'Uber focado',gym_study:'Academia + estudo',study:'Estudos',gym:'Academia',rest:'Descanso'};
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const week=d=>{const x=new Date(d+'T12:00:00');x.setDate(x.getDate()-(x.getDay()+6)%7);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}-${String(x.getDate()).padStart(2,'0')}`};
const schema={
 work_shifts:[['shift_date','Data','date'],['shift_type','Turno','select',['regular','early','late','off','custom']],['start_time','Entrada','time'],['end_time','Saída','time'],['notes','Observações','text']],
 activities:[['activity_date','Data','date'],['category','Categoria','select',['gym','study','english','uber','personal','work','commute','leisure','other']],['title','Atividade','text'],['start_time','Início','time'],['end_time','Fim','time']],
 uber_sessions:[['session_date','Data','date'],['strategy','Estratégia','select',['return','focused','weekend','other']],['trips','Corridas','number'],['gross_earnings','Receita bruta (R$)','number'],['distance_km','Distância (km)','number'],['started_at','Início da sessão (horário local)','datetime-local'],['ended_at','Fim da sessão (horário local)','datetime-local'],['notes','Observações','text']],
 study_sessions:[['session_date','Data','date'],['subject','Matéria','select',['NSE4','English','CompTIA','Fortinet Lab','Other']],['topic','Tema','text'],['duration_minutes','Duração (minutos)','number'],['questions_done','Questões','number'],['score_percent','Acertos (%)','number']],
 weekly_goals:[['week_start','Segunda-feira da semana','date'],['category','Categoria','select',['gym','study','english','uber','other']],['target_count','Meta','number'],['unit','Unidade','select',['sessions']]],
 routine_settings:[['default_wake_time','Acordar','time'],['default_sleep_time','Dormir','time'],['default_work_start','Entrada padrão','time'],['default_work_end','Saída padrão','time'],['commute_minutes','Deslocamento (min)','number'],['gym_weekly_target','Academia / semana','number'],['study_weekly_target','Estudos / semana','number'],['uber_weekly_target','Uber / semana','number']]
};
function Form({table,onSave,busy,initial={}}){return <form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget),r={};schema[table].forEach(([k,,t])=>{const v=f.get(k);if(v!=='')r[k]=t==='number'?Number(v):v});onSave(r)}} className="formgrid">{schema[table].map(([k,label,type,options])=><label key={k}>{label}{type==='select'?<select name={k} defaultValue={initial[k]||options[0]}>{options.map(o=><option key={o} value={o}>{labels[o]||o}</option>)}</select>:<input name={k} type={type} {...(type==='number'?fieldLimits(k):{})} required={['shift_date','activity_date','session_date','week_start','title'].includes(k)} defaultValue={initial[k]??(type==='date'?(k==='week_start'?week(today()):today()):'')}/>}</label>)}<button disabled={busy}>Salvar</button></form>}
export default function App(){
 const [db,setDb]=useState(null),[user,setUser]=useState(null),[ready,setReady]=useState(false),[data,setData]=useState({}),[tab,setTab]=useState('Hoje'),[date,setDate]=useState(today),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[authMode,setAuthMode]=useState('login'),[energy,setEnergy]=useState(3),[mode,setMode]=useState('auto'),[month,setMonth]=useState(today().slice(0,7));
 useEffect(()=>{const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;if(!url||!key){setNotice('Configure a conexão Supabase para iniciar.');setReady(true);return}const client=createClient(url,key);setDb(client);client.auth.getUser().then(({data})=>{setUser(data.user);setReady(true)});const {data:{subscription}}=client.auth.onAuthStateChange((_e,s)=>{setUser(s?.user??null);if(!s)setData({})});return()=>subscription.unsubscribe()},[]);
 async function load(){if(!db||!user)return;const results=await Promise.all(tables.map(t=>db.from(t).select('*').eq(t==='profiles'?'id':'user_id',user.id)));let next={};results.forEach((r,i)=>{if(r.error)throw new Error(`${tables[i]}: ${r.error.message}`);next[tables[i]]=r.data});setData(next)}
 useEffect(()=>{load().catch(e=>setNotice(e.message))},[db,user]);
 async function run(fn){setBusy(true);setNotice('');try{await fn();setNotice('Salvo com sucesso.');return true}catch(e){setNotice(e.message);return false}finally{setBusy(false)}}
 async function save(table,row){return await run(async()=>{row=prepareRow(table,row);const owner=table==='routine_settings'?{user_id:user.id}:{user_id:user.id};let q=db.from(table);const result=table==='routine_settings'?await q.upsert({...owner,...row},{onConflict:'user_id'}):await q.insert({...owner,...row});if(result.error)throw result.error;await load()})}
 const activities=data.activities||[],settings=data.routine_settings?.[0]||{},shifts=data.work_shifts||[],plans=data.daily_plans||[],ws=week(date);
 const progress=cat=>cat==='uber'?(data.uber_sessions||[]).filter(x=>week(x.session_date)===ws).length:cat==='study'?(data.study_sessions||[]).filter(x=>week(x.session_date)===ws&&x.subject!=='English').length:cat==='english'?(data.study_sessions||[]).filter(x=>week(x.session_date)===ws&&x.subject==='English').length:activities.filter(x=>x.category===cat&&x.completed&&week(x.activity_date)===ws).length;
 const shift=shifts.find(x=>x.shift_date===date),suggestion=planDay({shift,settings,energy,mode,progress:{gym:progress('gym'),study:progress('study')}}),dayActivities=activities.filter(x=>x.activity_date===date).sort((a,b)=>(a.start_time||'').localeCompare(b.start_time||''));
 async function generate(){await run(async()=>{let existing=plans.find(p=>p.plan_date===date);if(existing?.locked)throw Error('Este plano está bloqueado.');if(dayActivities.length)throw Error('Este dia já possui atividades. Ajuste-as manualmente para preservar seu planejamento.');const row={user_id:user.id,plan_date:date,selected_mode:mode,recommended_mode:suggestion.mode,energy_level:Number(energy),generated_plan:suggestion};const result=existing?await db.from('daily_plans').update(row).eq('id',existing.id).eq('user_id',user.id).select().single():await db.from('daily_plans').insert(row).select().single();if(result.error)throw result.error;if(suggestion.items.length){const a=await db.from('activities').insert(suggestion.items.map(x=>({...x,user_id:user.id,daily_plan_id:result.data.id,activity_date:date})));if(a.error)throw a.error}await load()})}
 async function toggle(a){await run(async()=>{const r=await db.from('activities').update({completed:!a.completed,completed_at:a.completed?null:new Date().toISOString()}).eq('id',a.id).eq('user_id',user.id);if(r.error)throw r.error;await load()})}
 const noticeUI=notice&&<p role="status" className="notice">{notice}</p>;
 if(!ready)return <main className="login"><p>Carregando sua rotina…</p></main>;
 if(!user)return <main className="login"><section className="loginCard"><div className="logo">r<span>•</span></div><p className="eyebrow">UM DIA DE CADA VEZ</p><h1>Seu tempo.<br/>Seu equilíbrio.</h1><p>Trabalho, saúde e objetivos em uma rotina que acompanha você.</p><form onSubmit={async e=>{e.preventDefault();if(!db)return;const f=new FormData(e.currentTarget);setBusy(true);setNotice('');const credentials={email:f.get('email'),password:f.get('password')};const r=authMode==='signup'?await db.auth.signUp(credentials):await db.auth.signInWithPassword(credentials);setBusy(false);setNotice(r.error?r.error.message:authMode==='signup'?'Confira seu e-mail para confirmar o cadastro.':'');}}><label>E-mail<input type="email" name="email" required autoComplete="email"/></label><label>Senha<input type="password" name="password" required minLength={8} autoComplete={authMode==='signup'?'new-password':'current-password'}/></label><button disabled={busy||!db}>{busy?'Aguarde…':authMode==='signup'?'Criar conta':'Entrar'}</button></form><button className="link" onClick={()=>setAuthMode(authMode==='login'?'signup':'login')}>{authMode==='login'?'Criar minha conta':'Já tenho uma conta'}</button>{noticeUI}</section></main>;
 return <div className="shell"><MobileNavigation tab={tab} email={user.email} onSelect={name=>{setTab(name);window.scrollTo({top:0,behavior:"instant"})}} onSignOut={()=>db.auth.signOut().then(r=>{if(r.error)setNotice(r.error.message)})}/><aside><div className="brand"><div className="logo">r<span>•</span></div><b>rotina<br/>dinâmica</b></div><p className="eyebrow">SEU ESPAÇO</p><nav>{['Hoje','Escala','Planejamento','Uber','Finanças','Academia','Estudos','Metas','Histórico','Preferências'].map((name,i)=><button className={tab===name?'active':''} key={name} onClick={()=>setTab(name)}><span>{['◉','▦','◇','↗','$','✦','▤','◎','◷','⚙'][i]}</span>{name}</button>)}</nav><div className="asideFooter"><small>{user.email}</small><button className="link" onClick={()=>db.auth.signOut().then(r=>{if(r.error)setNotice(r.error.message)})}>Sair da conta</button></div></aside><main className="content"><header><div><p className="eyebrow">ROTINA DINÂMICA</p><h1>{tab==='Hoje'?'Faça espaço para o que importa.':tab}</h1><p>{new Date(date+'T12:00:00').toLocaleDateString('pt-BR',{weekday:'long',day:'numeric',month:'long'})}</p></div><input aria-label="Dia selecionado" type="date" value={date} onChange={e=>e.target.value&&setDate(e.target.value)}/></header>{noticeUI}
 {tab==='Hoje'&&<><div className="hero"><div><p className="eyebrow">SEU DIA, COM INTENÇÃO</p><h2>{shift?.shift_type==='off'?'Hoje é dia de folga.':shift?'Seu trabalho está no calendário.':'Comece pela sua escala.'}</h2><p>{shift&&shift.shift_type!=='off'?`${shift.start_time?.slice(0,5)} — ${shift.end_time?.slice(0,5)}`:'Ajuste seus horários e encontre espaço para os seus objetivos.'}</p><button onClick={()=>setTab('Planejamento')}>Planejar meu dia ↗</button></div><div className="heroOrb">{dayActivities.filter(a=>a.completed).length}<small>atividades feitas</small></div></div><div className="stats">{['gym','study','uber'].map(cat=><article key={cat}><p>{labels[cat]} nesta semana</p><strong>{progress(cat)}<small> sessões</small></strong></article>)}</div><section><div className="sectionHead"><h2>O seu dia</h2><span>{dayActivities.length} atividades</span></div>{dayActivities.length?dayActivities.map(a=><div className="activity" key={a.id}><input type="checkbox" aria-label={`Concluir ${a.title}`} checked={a.completed} disabled={busy} onChange={()=>toggle(a)}/><span className="time">{a.start_time?.slice(0,5)||'Livre'}</span><div><b className={a.completed?'done':''}>{a.title}</b><p>{labels[a.category]||a.category} · {a.end_time?.slice(0,5)||'Sem horário final'}</p></div></div>):<p className="empty">Seu dia ainda está em branco. Gere uma sugestão no planejamento.</p>}</section></>}
 {tab==='Escala'&&<><section><div className="sectionHead"><h2>Calendário de trabalho</h2><input aria-label="Mês" type="month" value={month} onChange={e=>setMonth(e.target.value)}/></div><div className="calendar">{month&&Array.from({length:new Date(Number(month.slice(0,4)),Number(month.slice(5)),0).getDate()},(_,i)=>{const d=`${month}-${String(i+1).padStart(2,'0')}`,s=shifts.find(x=>x.shift_date===d);return <button key={d} className={d===date?'selected':''} onClick={()=>setDate(d)}><b>{i+1}</b><small>{new Date(d+'T12:00:00').toLocaleDateString('pt-BR',{weekday:'short'})}</small><span>{s?s.shift_type==='off'?'Folga':`${s.start_time?.slice(0,5)}–${s.end_time?.slice(0,5)}`:'Sem escala'}</span></button>})}</div></section><section><h2>Adicionar turno</h2><Form key={date} table="work_shifts" busy={busy} initial={{shift_date:date}} onSave={r=>{if(shifts.some(s=>s.shift_date===r.shift_date)){setNotice('Já há turno neste dia.');return}save('work_shifts',r)}}/></section></>}
 {tab==='Planejamento'&&<><section><h2>Planejamento dinâmico</h2><p>Sem escala cadastrada, a sugestão usa seu expediente padrão. Turnos noturnos precisam de planejamento manual.</p><div className="formgrid"><label>Energia<select value={energy} onChange={e=>setEnergy(Number(e.target.value))}>{[1,2,3,4,5].map(n=><option key={n}>{n}</option>)}</select></label><label>Foco do dia<select value={mode} onChange={e=>setMode(e.target.value)}>{Object.entries(modes).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label></div><h3>{modes[suggestion.mode]}</h3><p>{suggestion.reason}</p>{suggestion.items.map((a,i)=><div className="activity" key={i}><span className="time">{a.start_time} — {a.end_time}</span><b>{a.title}</b></div>)}<button disabled={busy||!suggestion.items.length} onClick={generate}>Salvar sugestão para {date}</button></section><section><h2>Adicionar atividade manual</h2><Form table="activities" initial={{activity_date:date}} busy={busy} onSave={r=>save('activities',r)}/></section></>}
 {tab==='Uber'&&<><div className="stats"><article><p>Receita bruta registrada</p><strong>{(data.uber_sessions||[]).reduce((s,r)=>s+Number(r.gross_earnings||0),0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</strong><small>Antes de despesas e custos de energia</small></article><article><p>Corridas</p><strong>{(data.uber_sessions||[]).reduce((s,r)=>s+r.trips,0)}</strong></article></div><section><h2>Registrar sessão</h2><Form table="uber_sessions" busy={busy} onSave={r=>save('uber_sessions',r)}/></section></>}
 {tab==='Finanças'&&<FinanceModule key={user.id} db={db} user={user} date={date} uberSessions={data.uber_sessions||[]} onGoUber={()=>setTab('Uber')}/>}
 {tab==='Academia'&&<section><h2>Treinos e consistência</h2><p>{progress('gym')} treinos concluídos nesta semana. Marque o treino no painel Hoje quando terminar.</p><Form table="activities" initial={{category:'gym',title:'Treino de academia'}} busy={busy} onSave={r=>save('activities',{...r,category:'gym'})}/></section>}
 {tab==='Estudos'&&<><StudyModule sessions={data.study_sessions||[]} date={date} busy={busy} onSave={r=>save('study_sessions',r)}/><section><h2>Registrar estudo livre</h2><p>Acompanhe seus temas, tempo de dedicação e resultados.</p><Form table="study_sessions" busy={busy} onSave={r=>save('study_sessions',r)}/></section></>}
 {tab==='Metas'&&<><section><h2>Semana de {ws}</h2>{(data.weekly_goals||[]).filter(g=>g.week_start===ws).map(g=><div className="goal" key={g.id}><div><b>{labels[g.category]||g.category}</b><span>{progress(g.category)} / {g.target_count} sessões</span></div><progress max={Math.max(1,Number(g.target_count))} value={progress(g.category)}/></div>)}</section><section><h2>Definir meta semanal</h2><Form table="weekly_goals" busy={busy} onSave={r=>save('weekly_goals',r)}/></section></>}
 {tab==='Histórico'&&<section><h2>Seus registros</h2>{[...activities.map(x=>({...x,display:x.title,date:x.activity_date,detail:x.completed?'Concluída':'Planejada'})),...(data.uber_sessions||[]).map(x=>({...x,display:'Uber',date:x.session_date,detail:`${x.trips} corridas · R$ ${x.gross_earnings||0}`})),...(data.study_sessions||[]).map(x=>({...x,display:x.subject,date:x.session_date,detail:`${x.duration_minutes||0} min · ${x.topic||''}`}))].sort((a,b)=>b.date.localeCompare(a.date)).map(x=><div className="activity" key={x.id}><span className="time">{x.date}</span><div><b>{x.display}</b><p>{x.detail}</p></div></div>)}</section>}
 {tab==='Preferências'&&<section><h2>Uma rotina que respeita seus horários</h2><Form key={JSON.stringify(settings)} table="routine_settings" initial={settings} busy={busy} onSave={r=>save('routine_settings',r)}/></section>}
 <footer>Uma rotina possível vale mais que um dia perfeito.</footer></main></div>
}
