'use client';
import {useEffect,useState} from 'react';
import {examSources,parseAnswerKey,gradeExam} from '../lib/exams.mjs';
export default function ExamPractice({date,busy,onSave}){
 const exam=examSources[0];const [keyText,setKeyText]=useState(''),[key,setKey]=useState(null),[answers,setAnswers]=useState({}),[result,setResult]=useState(null),[error,setError]=useState(''),[confirmed,setConfirmed]=useState(false),[saved,setSaved]=useState(false),[pdf,setPdf]=useState(null),[filter,setFilter]=useState('all');
 useEffect(()=>()=>{if(pdf)URL.revokeObjectURL(pdf)},[pdf]);
 function prepare(){try{setKey(parseAnswerKey(keyText));setAnswers({});setResult(null);setError('');setSaved(false)}catch(e){setError(e.message)}}
 async function save(){const ok=await onSave({session_date:date,subject:'Other',topic:`exam:${exam.id}`,questions_done:result.total-result.blank.length,score_percent:result.percent,notes:`${exam.name}; gabarito informado pelo usuário; acertos ${result.correct}/${result.total}; erros ${result.wrong.join(', ')||'nenhum'}; em branco ${result.blank.join(', ')||'nenhum'}; anuladas excluídas`});if(ok)setSaved(true);}
 const numbers=key?Object.keys(key).map(Number).sort((a,b)=>a-b).filter(n=>filter==='all'||result?.wrong.includes(String(n))):[];
 return <section><p className="eyebrow">QUESTÕES DE CONCURSOS ANTERIORES</p><h2>Resolver prova da AOCP</h2><h3>{exam.name}</h3><p>{exam.fit}</p>
 <p><a href={exam.official} target="_blank" rel="noreferrer">Página oficial do concurso ↗</a> · <a href={exam.documents} target="_blank" rel="noreferrer">Cadernos e gabarito definitivo ↗</a> · <a href={exam.archive} target="_blank" rel="noreferrer">Acervo alternativo ↗</a></p>
 <p>O caderno e o gabarito não foram importados: a página oficial abriu sem opções de download nesta verificação. Baixe os arquivos, confira cargo e tipo de prova e use o espaço abaixo. Os quizzes das aulas continuam sendo autorais.</p>
 <label>Caderno PDF no seu dispositivo<input type="file" accept="application/pdf,.pdf" onChange={e=>{const file=e.target.files?.[0];if(file)setPdf(URL.createObjectURL(file))}}/></label>
 {pdf&&<><p>O PDF é aberto apenas neste dispositivo e não é enviado ao banco.</p><iframe title="Caderno de questões selecionado" src={pdf} className="examPdf"/><a href={pdf} target="_blank" rel="noreferrer">Abrir PDF em outra aba</a></>}
 {!key?<><label>Gabarito definitivo do mesmo tipo de prova<textarea rows={7} value={keyText} onChange={e=>setKeyText(e.target.value)} placeholder={'1 A\n2 C\n3 X'}/></label><label className="quizOption"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>Conferi cargo, tipo de caderno e gabarito definitivo.</label><p>Uma linha por número e letra. X indica anulada. A correção depende do gabarito que você informa.</p><button disabled={!confirmed||!keyText.trim()} onClick={prepare}>Iniciar resolução</button></>:<><p>Leia cada questão no PDF, marque uma alternativa e confira ao terminar. Anuladas ficam fora da porcentagem de treino.</p>{result&&<label>Exibir<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Todas as questões</option><option value="wrong">Somente erros para revisar</option></select></label>}
 <div className="examAnswers">{numbers.map(n=><fieldset key={n} disabled={!!result||key[n]==='X'}><legend>Questão {n}{key[n]==='X'?' · anulada':''}</legend>{['A','B','C','D','E'].map(letter=><label className="quizOption" key={letter}><input type="radio" name={`exam-${n}`} checked={answers[n]===letter} onChange={()=>setAnswers({...answers,[n]:letter})}/>{letter}</label>)}{result&&key[n]!=='X'&&<p>{answers[n]===key[n]?'Correta':answers[n]?'Incorreta':'Em branco'} · Gabarito informado: {key[n]}</p>}</fieldset>)}</div>
 {!result?<button onClick={()=>setResult(gradeExam(key,answers))}>Corrigir tentativa</button>:<div role="status"><h3>{result.correct}/{result.total} · {result.percent}%</h3><p>{result.wrong.length} erros · {result.blank.length} em branco · {result.annulled.length} anuladas. Este percentual de treino não reproduz necessariamente a pontuação oficial.</p><p>Para fixar: releia cada erro, explique por que a alternativa correta atende ao enunciado e anote o assunto a revisar.</p><button disabled={busy||saved||result.total===0} onClick={save}>{saved?'Tentativa registrada':'Salvar tentativa no histórico'}</button><button className="link" onClick={()=>{setAnswers({});setResult(null);setSaved(false);setFilter('all')}}>Refazer prova</button></div>}
 <button className="link" onClick={()=>{setKey(null);setResult(null);setSaved(false);setConfirmed(false);setFilter('all')}}>Trocar gabarito</button></>}{error&&<p role="alert">{error}</p>}</section>
}
