'use client';
import {useEffect,useState} from 'react';
import {financeSources,financeKinds,moneyCents,currency,prepareFinanceRow,ledgerEntries,summarizeFinance,reserveBalance,uberHourly,financeCsv} from '../lib/finance.mjs';
function EntryForm({initial,date,reserves,busy,onSave,onCancel}) {
 const [kind,setKind]=useState(initial?.kind||'expense'),[source,setSource]=useState(initial?.source||'airbnb'),[status,setStatus]=useState(initial?.status||'settled');
 const reserve=['allocation','release'].includes(kind);
 return <form onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;const values=Object.fromEntries(new FormData(form));if(await onSave({...values,source:reserve?'personal':source,status:reserve?'settled':status},initial)){if(!initial){form.reset();setKind('expense');setSource('airbnb');setStatus('settled')}}}}><fieldset className="financeFields" disabled={busy}><div className="formgrid">
 <label>Tipo<select name="kind" value={kind} onChange={e=>setKind(e.target.value)}>{Object.entries(financeKinds).map(([key,value])=><option key={key} value={key}>{value}</option>)}</select></label>
 {!reserve&&<label>Origem<select name="source" value={source} onChange={e=>setSource(e.target.value)}>{Object.entries(financeSources).map(([key,value])=><option key={key} value={key}>{value}</option>)}</select></label>}
 <label>Descrição<input name="description" required maxLength={300} defaultValue={initial?.description||''} placeholder="Ex.: reserva de outubro, limpeza, salário"/></label>
 <label>Valor (R$)<input name="amount" type="number" inputMode="decimal" required min="0.01" max="9999999999.99" step="0.01" defaultValue={initial?.amount||''}/></label>
 <label>Data prevista / vencimento<input name="transaction_date" type="date" required defaultValue={initial?.transaction_date||date}/></label>
 {!reserve&&<label>Situação<select name="status" value={status} onChange={e=>setStatus(e.target.value)}><option value="settled">Recebido / pago</option><option value="pending">A receber / a pagar</option></select></label>}
 {(reserve||status==='settled')&&<label>Data de recebimento / pagamento<input name="settled_date" type="date" required defaultValue={initial?.settled_date||date}/></label>}
 {!reserve&&<label>Categoria<input name="category" maxLength={120} defaultValue={initial?.category||''} placeholder="Ex.: limpeza, taxa, combustível, salário"/></label>}
 {!reserve&&source==='airbnb'&&<label>Imóvel<input name="property_name" required maxLength={120} defaultValue={initial?.property_name||''} placeholder="Ex.: apartamento Centro"/></label>}
 {reserve&&<label>Reserva<select name="reserve_id" required defaultValue={initial?.reserve_id||''}><option value="">Escolha uma reserva</option>{reserves.map(r=><option value={r.id} key={r.id}>{r.name}</option>)}</select></label>}
 </div>{source==='airbnb'&&!reserve&&kind==='income'&&<p>Se registrar o valor líquido recebido, não lance novamente as taxas já descontadas. Se registrar o bruto, inclua as taxas como despesas do mesmo imóvel.</p>}
 {source==='uber'&&!reserve&&kind==='income'?<p>As receitas vêm das sessões da área Uber. Cadastre a sessão lá para evitar duplicidade; aqui você pode registrar combustível e outros custos.</p>:<button disabled={reserve&&reserves.length===0}>{busy?'Salvando…':initial?'Salvar alterações':'Adicionar lançamento'}</button>}
 {reserve&&<p>Este registro organiza o dinheiro que você separou; não movimenta uma conta bancária.</p>}
 {onCancel&&<button className="link" type="button" onClick={onCancel}>Cancelar edição</button>}</fieldset></form>;
}
export default function FinanceModule({db,user,date,uberSessions,onGoUber}) {
 const [transactions,setTransactions]=useState([]),[reserves,setReserves]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[month,setMonth]=useState(date.slice(0,7)),[filter,setFilter]=useState('all'),[editing,setEditing]=useState(null),[confirmDelete,setConfirmDelete]=useState(null);
 useEffect(()=>setMonth(date.slice(0,7)),[date]);
 async function load(signal){setLoading(true);setError('');try{
  const results=await Promise.all(['finance_transactions','finance_reserves'].map(table=>{let query=db.from(table).select('*').eq('user_id',user.id);if(signal)query=query.abortSignal(signal);return query;}));
  if(signal?.aborted)return;for(const result of results)if(result.error)throw result.error;
  setTransactions(results[0].data);setReserves(results[1].data);
 }catch(e){if(!signal?.aborted)setError(e.code==='PGRST205'||e.code==='42P01'?'A área financeira precisa ser ativada no banco antes do primeiro uso.':`Não foi possível carregar as finanças: ${e.message}`)}finally{if(!signal?.aborted)setLoading(false)}}
 useEffect(()=>{const controller=new AbortController();load(controller.signal);return()=>controller.abort()},[db,user.id]);
 async function perform(fn){setBusy(true);setNotice('');try{await fn();return true}catch(e){setNotice(e.message);return false}finally{setBusy(false)}}
 async function saveEntry(values,original){return perform(async()=>{
  const row=prepareFinanceRow(values);
  let query=original?db.from('finance_transactions').update(row).eq('id',original.id).eq('user_id',user.id).eq('updated_at',original.updated_at):db.from('finance_transactions').insert({...row,user_id:user.id});
  const result=await query.select().maybeSingle();if(result.error)throw result.error;if(!result.data)throw Error('O lançamento mudou em outra sessão. Recarregue os dados antes de editar.');
  setTransactions(previous=>[...previous.filter(x=>x.id!==result.data.id),result.data]);setEditing(null);setNotice('Lançamento salvo.');
 });}
 async function settle(row){await saveEntry({...row,status:'settled',settled_date:date},row)}
 async function remove(row){await perform(async()=>{const result=await db.from('finance_transactions').delete().eq('id',row.id).eq('user_id',user.id).eq('updated_at',row.updated_at).select('id');if(result.error)throw result.error;if(!result.data?.length)throw Error('O lançamento mudou. Recarregue antes de excluir.');setTransactions(previous=>previous.filter(x=>x.id!==row.id));if(editing?.id===row.id)setEditing(null);setConfirmDelete(null);setNotice('Lançamento excluído.');});}
 async function addReserve(e){e.preventDefault();const form=e.currentTarget;const values=Object.fromEntries(new FormData(form));await perform(async()=>{const target=moneyCents(values.target_amount);if(!target)throw Error('A meta deve ser maior que zero.');const result=await db.from('finance_reserves').insert({user_id:user.id,name:values.name.trim(),target_amount:(target/100).toFixed(2)}).select().single();if(result.error)throw result.error;setReserves(previous=>[...previous,result.data]);form.reset();setNotice('Reserva criada. Agora registre o valor que você separou.');});}
 if(loading)return <section><p role="status">Carregando suas finanças…</p></section>;
 if(error)return <section><h2>Finanças indisponíveis</h2><p role="alert">{error}</p><button onClick={()=>load()}>Tentar novamente</button></section>;
 const entries=ledgerEntries(transactions,uberSessions),summary=summarizeFinance(entries,month,date),hourly=uberHourly(uberSessions,month);
 const monthly=entries.filter(e=>(e.status==='settled'?e.settled_date:e.transaction_date)?.slice(0,7)===month),visible=monthly.filter(e=>filter==='all'||e.source===filter).sort((a,b)=>(b.settled_date||b.transaction_date).localeCompare(a.settled_date||a.transaction_date));
 function exportCsv(){const url=URL.createObjectURL(new Blob([financeCsv(visible)],{type:'text/csv;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download=`financas-${month}.csv`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 return <div className="financeModule"><section><div className="sectionHead"><h2>Seu dinheiro, com clareza</h2><label>Mês financeiro<input type="month" value={month} onChange={e=>e.target.value&&setMonth(e.target.value)}/></label></div><p>Receitas recebidas, despesas pagas e valores previstos. O saldo mostra o movimento do período registrado, não o saldo da sua conta bancária.</p>
 <div className="stats financeStats">{[['Recebido',summary.income],['Pago',summary.expenses],['Resultado do mês',summary.net],['Livre após reservas',summary.available]].map(([label,value])=><article key={label}><p>{label}</p><strong className={value<0?'financeNegative':''}>{currency(value)}</strong></article>)}</div>
 <p>A receber: <strong>{currency(summary.pendingIncome)}</strong> · A pagar: <strong>{currency(summary.pendingExpenses)}</strong> · Separado para reservas: {currency(summary.allocated)} · Retirado das reservas: {currency(summary.released)}</p>
 <p>As receitas Uber registradas são consideradas recebidas na data da sessão. Elas entram automaticamente uma única vez. Confira se todos os custos foram lançados antes de interpretar o resultado.</p><button className="link" onClick={onGoUber}>Registrar receita ou horário de sessão Uber →</button>
 </section>{notice&&<p className="notice" role="status">{notice}</p>}
 <section><h2>Resultado por atividade</h2><div className="financeSourceGrid">{summary.sources.map(s=><article className="studyCard" key={s.source}><h3>{financeSources[s.source]}</h3><p>Receitas: {currency(s.revenue)}<br/>Despesas: {currency(s.cost)}</p><strong>Resultado registrado: {currency(s.net)}</strong></article>)}</div>
 <p>Uber · receita bruta por hora: {hourly.rate===null?'informe início e fim das sessões na área Uber':currency(hourly.rate)}{hourly.count>0&&` · ${hourly.count} sessões com horários · ${hourly.hours.toFixed(1)} horas`}. O cálculo por hora considera somente as sessões com horários completos.</p>
 {summary.properties.length>0&&<><h3>Airbnb por imóvel</h3>{summary.properties.map(p=><div className="activity" key={p.name}><div><b>{p.name}</b><p>Receitas {currency(p.revenue)} · Custos {currency(p.cost)} · Resultado {currency(p.net)}</p></div></div>)}</>}
 </section>
 <section><h2>Contas vencidas e próximos vencimentos</h2><p>Contas vencidas até {date}, incluindo meses anteriores.</p>{summary.overdue.length?summary.overdue.map(row=><div className="financeEntry" key={row.id}><div><b>{row.description}</b><p>{row.kind==='income'?'A receber':'A pagar'} · {row.transaction_date} · {currency(moneyCents(row.amount))}</p></div><button disabled={busy} onClick={()=>settle(row)}>Confirmar em {date}</button></div>):<p>Nenhuma conta vencida registrada.</p>}
 <h3>Previsto para {month}</h3>{monthly.filter(e=>e.status==='pending'&&e.transaction_date>=date).map(row=><div className="financeEntry" key={row.id}><div><b>{row.description}</b><p>{row.transaction_date} · {row.kind==='income'?'A receber':'A pagar'} · {currency(moneyCents(row.amount))}</p></div><button disabled={busy} onClick={()=>settle(row)}>Confirmar em {date}</button></div>)}
 <p>Ao confirmar, o valor entra no mês da data de recebimento/pagamento. Use editar se a data real for diferente.</p></section>
 <section><h2>{editing?'Editar lançamento':'Adicionar receita, despesa ou reserva'}</h2><EntryForm key={editing?.id||`new-${date}`} initial={editing} date={date} reserves={reserves} busy={busy} onSave={saveEntry} onCancel={editing?()=>setEditing(null):null}/></section>
 <section><h2>Reservas e metas</h2><p>Valores separados até {date}. Aportes reduzem o livre do mês, mas não são despesas; retiradas fazem o caminho inverso.</p>
 {reserves.map(r=>{const balance=reserveBalance(entries,r.id,date),target=moneyCents(r.target_amount);return <article className="studyCard" key={r.id}><h3>{r.name}</h3><p>{currency(balance)} de {currency(target)} · faltam {currency(Math.max(0,target-balance))}</p><progress aria-label={`Meta ${r.name}`} max={target} value={Math.max(0,balance)}/></article>})}
 <form onSubmit={addReserve}><fieldset className="financeFields" disabled={busy}><div className="formgrid"><label>Nome da reserva<input name="name" required maxLength={120} placeholder="Ex.: emergência, manutenção do carro"/></label><label>Meta da reserva (R$)<input type="number" name="target_amount" required min="0.01" max="9999999999.99" step="0.01"/></label></div><button>Criar reserva</button></fieldset></form></section>
 <section><div className="sectionHead"><h2>Lançamentos do mês</h2><button className="link" onClick={exportCsv}>Exportar CSV</button></div><label>Filtrar origem<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Todas</option>{Object.entries(financeSources).map(([key,value])=><option key={key} value={key}>{value}</option>)}</select></label>
 {!visible.length&&<p>Nenhum lançamento nesse período e filtro.</p>}{visible.map(row=><article className="financeEntry" key={row.id}><div><b>{row.description}</b><p>{financeSources[row.source]} · {financeKinds[row.kind]} · {row.status==='settled'?'Confirmado':'Pendente'}<br/>{row.settled_date||row.transaction_date} · {currency(moneyCents(row.amount))}{row.property_name&&` · ${row.property_name}`}</p>{row.automatic&&<small>Receita automática da sessão Uber.</small>}</div><div className="financeActions">{row.automatic?<button className="link" onClick={onGoUber}>Ver Uber</button>:<><button className="link" disabled={busy} onClick={()=>{setEditing(row);setConfirmDelete(null)}}>Editar</button>{confirmDelete===row.id?<><span>Excluir este lançamento?</span><button disabled={busy} onClick={()=>remove(row)}>Confirmar exclusão</button><button className="link" onClick={()=>setConfirmDelete(null)}>Cancelar</button></>:<button className="link" disabled={busy} onClick={()=>setConfirmDelete(row.id)}>Excluir</button>}</>}</div></article>)}
 </section></div>;
}
