'use client';
import {useEffect,useState} from 'react';
import {tracks,lessonTopic,studyProgress} from '../lib/study.mjs';
export default function StudyModule({sessions,date,busy,onSave}){
 const [trackId,setTrackId]=useState('NSE4'),[lessonId,setLessonId]=useState(null),[stage,setStage]=useState(0),[answers,setAnswers]=useState({}),[submitted,setSubmitted]=useState(false),[saved,setSaved]=useState(false),[seconds,setSeconds]=useState(25*60),[running,setRunning]=useState(false),[focus,setFocus]=useState(false);
 const track=tracks.find(t=>t.id===trackId)||tracks[0],progress=studyProgress(track,sessions,date),lesson=track.lessons.find(l=>l.id===lessonId)||progress.next;
 useEffect(()=>{setStage(0);setAnswers({});setSubmitted(false);setSaved(false);setSeconds(1500);setRunning(false)},[trackId,lesson.id,date]);
 useEffect(()=>{if(!running)return;const end=Date.now()+seconds*1000;const id=setInterval(()=>{const left=Math.max(0,Math.ceil((end-Date.now())/1000));setSeconds(left);if(!left)setRunning(false)},250);return()=>clearInterval(id)},[running]);
 const score=lesson.quiz.reduce((n,q,i)=>n+(answers[i]===q.answer?1:0),0),scorePercent=Math.round(score/lesson.quiz.length*100);
 async function finish(){const ok=await onSave({session_date:date,subject:track.subject||track.id,topic:lessonTopic(track,lesson),duration_minutes:Math.max(1,Math.ceil((1500-seconds)/60)),questions_done:lesson.quiz.length,score_percent:scorePercent,notes:`${lesson.title}; ${scorePercent>=80?'Concluída':'Reforço recomendado'}`});if(ok)setSaved(true);}
 return <div className={focus?'studyModule studyFocus':'studyModule'}>
 <section><div className="sectionHead"><div><p className="eyebrow">APRENDER · PRATICAR · REVISAR</p><h2>Seu próximo passo nos estudos</h2></div><button className="link" onClick={()=>setFocus(!focus)}>{focus?'Sair do foco':'Modo foco'}</button></div>
 <label>Trilha<select value={trackId} onChange={e=>{setTrackId(e.target.value);setLessonId(null)}}>{tracks.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><p>{track.description}</p>
 <div className="studyPlan"><strong>{progress.review?'Revisão recomendada':'Estude hoje'}: {progress.next.title}</strong><p>{progress.completed} de {track.lessons.length} aulas com pelo menos 80% de acertos. Revisão sugerida após 3 dias.</p><progress aria-label="Progresso da trilha" max={track.lessons.length} value={progress.completed}/></div>
 {track.syllabus&&<details className="studyCard"><summary>Mapa completo de assuntos do edital</summary>{track.syllabus.map(([name,topics])=><article key={name}><h3>{name}</h3><p>{topics}</p></article>)}<p>As aulas disponíveis iniciam cada disciplina; o mapa inclui tópicos que ainda precisam de aulas aprofundadas.</p><a href={track.source} target="_blank" rel="noreferrer">Consultar PDF enviado</a></details>}<div className="lessonChoices">{track.lessons.map((l,i)=><button key={l.id} aria-pressed={lesson.id===l.id} onClick={()=>setLessonId(l.id)}>{i+1}. {l.title}</button>)}</div></section>
 <section><p className="eyebrow">AULA GUIADA · 25 MINUTOS</p><h2>{lesson.title}</h2><p><strong>Ao terminar:</strong> {lesson.goal}</p>
 <div className="studyTimer"><output aria-label="Tempo de foco restante">{String(Math.floor(seconds/60)).padStart(2,'0')}:{String(seconds%60).padStart(2,'0')}</output><button onClick={()=>setRunning(!running)} disabled={seconds===0}>{running?'Pausar':'Iniciar foco'}</button><button className="link" onClick={()=>{setRunning(false);setSeconds(1500)}}>Reiniciar</button><span>{seconds===0?'Hora de fazer uma pausa de 5 minutos.':'Silencie notificações. Faça uma etapa por vez.'}</span></div>
 <div className="studySteps" aria-label="Etapas da aula">{['Entender','Praticar','Relembrar','Testar'].map((s,i)=><button key={s} aria-pressed={stage===i} onClick={()=>setStage(i)}>{i+1}. {s}</button>)}</div>
 {stage===0&&<div>{lesson.sections.map(([title,text])=><article key={title}><h3>{title}</h3><p>{text}</p></article>)}<p><a href={track.source} target="_blank" rel="noreferrer">Continuar na fonte de referência ↗</a></p></div>}
 {stage===1&&<article><h3>Coloque em prática</h3><p>{lesson.practice}</p><p>Reserve 7 minutos. Ao terminar, explique sua resposta com suas próprias palavras.</p></article>}
 {stage===2&&<div><h3>Recorde antes de revelar</h3><p>Tente responder em voz alta e depois confira.</p>{lesson.cards.map(([front,back])=><details className="studyCard" key={front}><summary>{front}</summary><p>{back}</p></details>)}</div>}
 {stage===3&&<div><h3>Teste de fixação</h3><p>Responda sem consultar o material. As questões são autorais.</p>{lesson.quiz.map((q,i)=><fieldset key={q.prompt} disabled={submitted}><legend>{i+1}. {q.prompt}</legend>{q.options.map((o,j)=><label className="quizOption" key={o}><input type="radio" name={`${lesson.id}-${i}`} checked={answers[i]===j} onChange={()=>setAnswers({...answers,[i]:j})}/>{o}</label>)}{submitted&&<p>{answers[i]===q.answer?'Correto.':'Reveja este ponto.'} {q.explanation}</p>}</fieldset>)}
 {!submitted?<button disabled={Object.keys(answers).length!==lesson.quiz.length} onClick={()=>setSubmitted(true)}>Conferir respostas</button>:<div role="status"><h3>{score} de {lesson.quiz.length} · {scorePercent}%</h3><p>{scorePercent>=80?'Você atingiu a meta desta aula. Registre e continue na próxima sessão.':'Releia os pontos que errou e tente novamente para consolidar.'}</p><button disabled={busy||saved} onClick={finish}>{saved?'Resultado registrado':busy?'Salvando…':'Registrar sessão no meu histórico'}</button><button className="link" onClick={()=>{setAnswers({});setSubmitted(false)}}>Tentar novamente</button></div>}</div>}
 {stage<3&&<button onClick={()=>setStage(stage+1)}>Próxima etapa →</button>}
 </section><section><h2>Também estude para PMPE Soldado</h2><p>Selecione a trilha PMPE acima para consultar o mapa do edital enviado e estudar as aulas iniciais de cada disciplina.</p><button onClick={()=>{setTrackId("PMPE");setLessonId(null)}}>Abrir trilha PMPE</button></section></div>
}
