import {pmpe} from './pmpe.mjs';
export const tracks = [
 {id:'NSE4',name:'Fortinet: fundamentos',description:'Comece pela rede e avance para políticas de firewall. Material introdutório; não substitui o currículo oficial da certificação.',source:'https://training.fortinet.com/',lessons:[
  {id:'network',title:'Como os dados encontram o destino',goal:'Explicar IP, gateway e DNS e diagnosticar uma falha simples.',sections:[
   ['Endereço IP e rede','O endereço IPv4 identifica uma interface na rede. A máscara define quais endereços pertencem à mesma sub-rede. Em 192.168.10.20/24, a rede é 192.168.10.0 e o broadcast é 192.168.10.255. Os endereços usuais de hosts ficam entre .1 e .254.'],
   ['Gateway e DNS','Para alcançar outra rede, o computador normalmente envia os pacotes ao gateway padrão. DNS resolve nomes, como exemplo.com, em endereços IP. São funções diferentes: uma falha de DNS pode impedir acesso por nome mesmo quando há conectividade por IP.'],
   ['Diagnóstico por camadas','Confira a interface e o endereço local, depois a rota padrão e a resolução de nomes. Ping pode ajudar, mas sua ausência de resposta não prova falta de conectividade: ICMP pode estar bloqueado. Compare evidências antes de concluir.']],practice:'Desenhe notebook → gateway → internet. Use endereços fictícios. Explique em voz alta o que acontece quando o destino está fora da sub-rede e onde o DNS participa.',cards:[['Gateway','Encaminha tráfego para outras redes.'],['DNS','Resolve nomes em endereços.'],['/24','Máscara 255.255.255.0 no IPv4.']],quiz:[
   {prompt:'Um site abre por IP, mas não pelo nome. O que investigar primeiro?',options:['DNS','A cor do cabo','O tamanho do monitor'],answer:0,explanation:'A conectividade por IP funciona; a resolução de nomes é a primeira hipótese, sem excluir outras causas.'},
   {prompt:'Qual destino normalmente exige o gateway para um host 192.168.10.20/24?',options:['192.168.10.30','10.0.0.5','192.168.10.40'],answer:1,explanation:'10.0.0.5 está fora da sub-rede 192.168.10.0/24.'}]},
  {id:'policy',title:'Políticas de firewall e menor privilégio',goal:'Construir uma regra com origem, destino e serviço específicos.',sections:[['O que uma política decide','Uma política avalia o tráfego usando interfaces, endereços, serviços e outros critérios. No FortiGate, a ordem das políticas importa: a primeira regra correspondente é usada. Tráfego sem política permissiva correspondente é negado.'],['Menor privilégio','Permita apenas o necessário. Para um servidor web, defina origem apropriada, IP do servidor e HTTPS em vez de liberar todos os serviços para todos os destinos. Registrar eventos ajuda a confirmar o comportamento.'],['Estado da conexão','Firewalls com inspeção de estado acompanham sessões. O retorno de uma sessão permitida não é simplesmente uma nova conexão independente. Uma conexão iniciada no sentido inverso pode exigir outra política.']],practice:'No papel, desenhe uma política para uma rede de funcionários acessar um servidor interno por HTTPS. Anote interface de entrada, saída, origem, destino, serviço e ação. Não altere um firewall de produção.',cards:[['Menor privilégio','Permitir somente acessos necessários.'],['Ordem das políticas','A primeira política correspondente é usada.'],['Estado','Contexto de uma sessão acompanhada pelo firewall.']],quiz:[{prompt:'Qual regra é mais restrita?',options:['Qualquer origem e serviço','Funcionários → servidor específico, HTTPS','Internet → toda a rede, todos os serviços'],answer:1,explanation:'Origem, destino e serviço específicos reduzem a superfície permitida.'},{prompt:'Duas regras correspondem ao tráfego. Qual é usada?',options:['A primeira correspondente','A última sempre','As duas em paralelo'],answer:0,explanation:'A ordem das políticas determina a primeira correspondência.'}]},
  {id:'nat',title:'NAT, rotas e logs',goal:'Distinguir tradução de endereços, autorização e encaminhamento.',sections:[['NAT não é autorização','Source NAT pode traduzir o endereço de origem de clientes internos ao sair para a internet. Isso não substitui uma política que permita o tráfego. Destination NAT traduz o destino, por exemplo em uma publicação de serviço.'],['A rota escolhe o caminho','Uma rota informa por onde alcançar uma rede. Uma política permissiva não corrige uma rota ausente. Para investigar, separe três perguntas: há rota? a política permite? a tradução necessária está correta?'],['Logs como evidência','Observe horário, origem, destino, porta, ação e política nos logs. Compare com a tentativa de acesso. Evite concluir que a regra está correta apenas porque sua configuração parece adequada.']],practice:'Um cliente não acessa a internet. Crie uma lista de verificação com endereço, gateway, DNS, rota, política e NAT. Para cada item, indique qual evidência buscaria em um laboratório.',cards:[['SNAT','Tradução do endereço de origem.'],['Rota','Caminho para uma rede de destino.'],['Log','Evidência de um evento e de sua decisão.']],quiz:[{prompt:'Ativar NAT é suficiente para autorizar tráfego?',options:['Sim, sempre','Não; política e rota também importam','Somente aos domingos'],answer:1,explanation:'Tradução, autorização e encaminhamento são funções distintas.'},{prompt:'Qual evidência ajuda a entender uma negação?',options:['Log da tentativa com ação e política','Nome do notebook','Cor do firewall'],answer:0,explanation:'O log relaciona a tentativa à decisão aplicada.'}]}]},
 {id:'English',name:'Inglês para o dia a dia',description:'Vocabulário e estruturas básicas para falar da sua rotina.',source:'https://learnenglish.britishcouncil.org/',lessons:[
 {id:'routine',title:'Apresente sua rotina em inglês',goal:'Escrever cinco frases curtas sobre o seu dia.',sections:[['Vocabulário útil','Wake up = acordar; work = trabalhar; study = estudar; exercise = fazer exercício; rest = descansar. Exemplo: I study at night. = Eu estudo à noite.'],['Presente simples','Use I + verbo para hábitos: I work in the morning. Com he/she/it, o verbo normalmente recebe -s: She works in the morning. Para negar: I do not work on Sunday; She does not work on Sunday. Depois de does not, use work, sem -s.'],['Horários','Use at para horários: I wake up at seven. Use in the morning, in the afternoon e in the evening; para noite, at night. Leia cada frase e depois tente repeti-la sem olhar.']],practice:'Escreva cinco frases verdadeiras sobre sua rotina. Leia em voz alta e repita sem olhar. Troque duas frases de I para she, ajustando o verbo.',cards:[['I study at night.','Eu estudo à noite.'],['She works.','Ela trabalha.'],['I wake up at seven.','Eu acordo às sete.']],quiz:[{prompt:'Complete: She ___ every day.',options:['study','studies','studying'],answer:1,explanation:'No presente simples, study vira studies com she.'},{prompt:'Qual frase está correta?',options:['I wake up in seven.','I wake up at seven.','I wakes up at seven.'],answer:1,explanation:'Use at para horários e wake com I.'}]},
 {id:'questions',title:'Faça perguntas sobre hábitos',goal:'Perguntar e responder sobre trabalho e estudos.',sections:[['Do e does','Use Do you study? para você. Use Does she study? para ela. O verbo principal fica na forma base depois de does.'],['Respostas curtas','Do you work? Yes, I do. / No, I do not. Does he study? Yes, he does. / No, he does not. A resposta acompanha o auxiliar da pergunta.'],['Palavras de pergunta','What = o quê; where = onde; when = quando. What do you study? I study English. Where do you work? I work at an office.']],practice:'Escreva um diálogo de seis falas sobre trabalho e estudos. Faça três perguntas e responda sem copiar os exemplos.',cards:[['What do you study?','O que você estuda?'],['Does she work?','Ela trabalha?'],['Yes, I do.','Resposta afirmativa curta com do.']],quiz:[{prompt:'Qual pergunta está correta?',options:['Does she studies?','Does she study?','Do she studies?'],answer:1,explanation:'Does pede o verbo principal na forma base.'},{prompt:'Where pergunta sobre…',options:['Lugar','Horário','Quantidade'],answer:0,explanation:'Where significa onde.'}]}]},
 {id:'CompTIA',name:'Redes e suporte: fundamentos',description:'Base introdutória de redes e diagnóstico, sem prometer cobertura de um exame específico.',source:'https://www.comptia.org/',lessons:[
 {id:'protocols',title:'TCP, UDP e serviços de rede',goal:'Relacionar protocolos de transporte com serviços comuns.',sections:[['TCP','TCP oferece um fluxo de bytes ordenado, com mecanismos de retransmissão e controle. É usado por muitos serviços que precisam dessa confiabilidade de transporte. Ele não criptografa o conteúdo por si só.'],['UDP','UDP envia datagramas sem garantir entrega ou ordem no próprio protocolo. Aplicações podem implementar seus próprios mecanismos. DNS tradicional frequentemente usa UDP, mas também pode usar TCP; evite regras absolutas.'],['Portas e serviços','HTTPS costuma usar TCP 443; SSH, TCP 22. DNS tradicional usa porta 53 em UDP e TCP. Portas padrão ajudam a investigar, mas serviços podem ser configurados em outras portas.']],practice:'Monte uma tabela com HTTPS, SSH e DNS: função, porta padrão e transporte. Explique por que uma porta aberta não prova que um serviço está saudável.',cards:[['TCP','Fluxo ordenado com mecanismos de confiabilidade.'],['UDP','Datagramas sem garantia própria de entrega.'],['HTTPS','HTTP protegido por TLS; normalmente porta 443.']],quiz:[{prompt:'TCP sozinho criptografa o conteúdo?',options:['Sim','Não','Só na porta 22'],answer:1,explanation:'A criptografia depende de protocolos como TLS ou SSH.'},{prompt:'DNS tradicional pode usar…',options:['Somente UDP','TCP e UDP','Somente HTTPS'],answer:1,explanation:'DNS tradicional usa porta 53 em TCP e UDP.'}]},
 {id:'diagnosis',title:'Diagnóstico com hipóteses e evidências',goal:'Organizar uma investigação sem mudar configurações ao acaso.',sections:[['Defina o problema','Pergunte quem é afetado, quando começou e qual erro aparece. Diferencie um computador sem rede de um único aplicativo com falha.'],['Teste uma hipótese por vez','Verifique conexão física, endereço IP, rota, resolução de nomes e serviço. Registre resultado e próxima hipótese. Não desative controles de segurança apenas para fazer um teste passar.'],['Confirme e documente','Após a correção, repita a operação original. Uma resposta ao ping não confirma que o login de uma aplicação funciona. Documente causa, alteração e evidência de resolução.']],practice:'Um navegador mostra erro de nome não encontrado. Escreva três hipóteses e um teste para cada uma. Explique qual resultado confirmaria ou enfraqueceria cada hipótese.',cards:[['Escopo','Quem e quais serviços são afetados.'],['Hipótese','Explicação que pode ser testada.'],['Validação','Repetir a operação que falhava.']],quiz:[{prompt:'Qual teste confirma que um aplicativo voltou a funcionar?',options:['Somente ping','Repetir a operação original','Reiniciar sem verificar'],answer:1,explanation:'A verificação deve exercitar o comportamento que estava quebrado.'},{prompt:'Ao investigar, é melhor…',options:['Mudar tudo de uma vez','Testar uma hipótese e registrar o resultado','Desativar toda a segurança'],answer:1,explanation:'Uma mudança por vez permite relacionar causa e efeito.'}]}]}
];
tracks.push(pmpe);
export const lessonTopic=(track,lesson)=>`study:${track.id}:${lesson.id}`;
export function studyProgress(track,sessions,date){
 const records=sessions.filter(s=>s.subject===(track.subject||track.id)&&s.session_date<=date);
 const latest=l=>records.filter(s=>s.topic===lessonTopic(track,l)).sort((a,b)=>b.session_date.localeCompare(a.session_date)||(b.created_at||'').localeCompare(a.created_at||''))[0];
 const mastered=l=>Number(latest(l)?.score_percent)>=80;
 const completed=track.lessons.filter(mastered).length;
 const due=track.lessons.find(l=>{const r=latest(l);if(!r||!mastered(l))return false;return Math.floor((Date.parse(date+'T12:00:00Z')-Date.parse(r.session_date+'T12:00:00Z'))/86400000)>=3;});
 const next=due||track.lessons.find(l=>!mastered(l))||track.lessons[0];
 return {completed,next,review:!!due,latest};
}
